#:schema node_modules/wrangler/config-schema.json
name = "metowolf-ip"
main = "src/worker.js"
compatibility_date = "2024-11-11"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = "OPENIPDB_BUCKET"
bucket_name = "openipdb"

[observability.logs]
enabled = true