name: Build Releases
on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: ipdb-api/server

jobs:
  build-cross:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      contents: read
      packages: write
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Parse Version from package.json
        run: |
          echo IMAGE_VERSION=$(node -p "require('./package.json').version") >> $GITHUB_ENV
      - 
        name: Build and release Docker images
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          push: true